### ISSUE TITLE
Data issue in Paper Table 7 .

### ISSUE THREAD

**Issue by tambourine666** [ihaeyong/SoftNet-FSCIL#2]
Thank you for the inspiring paper in FSCIL!

When reading your paper, it seems that the experimental result of session 4 on CUB200 (Table 7 in the appendix, SoftNet, c = 93% ) is a little misleading. Is it a typo? Or it's the actual results?
<img width="1167" alt="截屏2023-08-07 10 33 23" src="https://github.com/ihaeyong/SoftNet-FSCIL/assets/71709069/8444468a-c5a6-4336-a2a1-01ac84c83e2c">

**Comment by ihaeyong** [comment]
Sorry for that point. It seems to be a typo: **67.27** to 62.27.
